Table of Content:

[Skeleton code for desired function](##Skeleton_code_for_desired_function)

[Plots](##Plots)

[Debugging](##Debugging)

[Extensions](##Extensions)

# Home Office Simulation

Write a python function that simulates the number of people present in an office when the n employees work from home 3 days a week and in the office 2 days.
In particular, the results should be:

1. Distribution of # employees in the office on a random day

For each simulated week:

Each of nnn employees randomly selects 2 distinct office days (from 5).

For each day, count how many employees chose that day.

Aggregate across simulations to approximate the distribution.

Plot a histogram

2. Probability that two particular employees overlap ≥ 2 days

For each simulated week:

Simulate their two chosen office days.

Count the overlap between them.

Record whether overlap ≥ 2.

## Skeleton code for desired function:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:


def office_simulation(n=20, n_weeks=1000, seed=None, plot=True):
    """
    Simulates office attendance given n employees each in-office 2 of 5 weekdays.

    Parameters
    ----------
    n : int
        Number of employees.
    n_weeks : int
        Number of simulated weeks.
    seed : int or None
        Random seed for reproducibility.
    plot : bool
        Whether to plot the resulting distribution.

    Returns
    -------
    dist : array
        Empirical distribution of #employees present on a random day.
    overlap_prob : float
        Probability that two specific employees overlap >=2 days per week.
    """

    rng = np.random.default_rng(seed)
    days = np.arange(5)

    day_counts = []
    overlap_count = 0

    for _ in range(n_weeks):
        # Each employee randomly chooses 2 distinct office days


        # Count how many employees come in on each day


        # Overlap between two particular employees (say #0 and #1)


    # Distribution of employees per day


        if plot:
            plt.figure(figsize=(7, 4))

            plt.xlabel("Number of employees in the office")
            plt.ylabel("Probability")
            plt.title(f"Distribution of employees in office (n={n})")
            plt.grid(alpha=0.3)
            plt.show()

    return dist, overlap_prob


Q: What is the avarge num employees in the office ?? (n=25)

A: 25 *(4/10) = 10

A: 8 or 10 or

n=25 90% the num will be between 5 and 16
"between 50% and 160%)

n = 2500 90% the num will be between ? and ?

"Bigger is better (risk)"


In [2]:
dist, overlap_prob = office_simulation(n=25, n_weeks=2000, seed=42)


print(f"\nP(two specific employees overlap ≥ 2 days/week): {overlap_prob:.4f}")


NameError: name 'office_simulation' is not defined

### One week, one employee:

In [ ]:
import numpy as np

rng = np.random.default_rng()


#simulate 2 random days in the office

#rng.integers(1,6,2) # this could create duplicates

# WAIT We need to set replace = FALSE !! Because there should be no duplicates!
empChoice = rng.choice(np.arange(1,6),2, replace = False )
weekdays = np.zeros(6)
print(weekdays)
print(empChoice)
#weekdays[0] += 1
#weekdays[4] += 1

weekdays[empChoice -1 ] += 1
weekdays




Now we go from one to n employees, so we need a loop !

In [ ]:
n = 20
weekdays = np.zeros(5, dtype = "int")
NumEmpInOffice = np.zeros(n+1, dtype = "int")

for i in range(n):
  empChoice = rng.choice(np.arange(1,6),2, replace = False )
  weekdays[empChoice -1 ] += 1


NumEmpInOffice[weekdays] += 1
print(weekdays)

if np.sum(weekdays)!= 2*n:
  print("sth. is wrong!") #sanity check!

NumEmpInOffice

Let us simulate MANY WEEKS !!

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def HomeOfficeSimulation(n = 20, n_weeks = 1000, daysInWeek = 5, seed=123, verbose = False):
  rng = np.random.default_rng(seed)

  NumEmpInOffice = np.zeros(n+1, dtype = "int")#this is a 1D array of length n+1
  for j in range(n_weeks):
    weekdays = np.zeros(daysInWeek, dtype = "int")#this is a 1D array of length 5

    for i in range(n):
      empChoice = rng.choice(np.arange(1,daysInWeek+1),2, replace = False )
      weekdays[empChoice -1 ] += 1#this is of length 5 !!

    #NumEmpInOffice[weekdays] += 1 #for each of 5 elements I increment by 1
    for w in weekdays:
      NumEmpInOffice[w] += 1

    if (verbose):
      print(weekdays)
      #print(NumEmpInOffice)
      print(pd.Series(NumEmpInOffice, index=range(n + 1)).to_dict())

    if np.sum(weekdays)!= 2*n:
      print("sth. is wrong!") #sanity check!
  #we would like to return the probability !
  #of course they have to add to one in total
  return NumEmpInOffice/np.sum(NumEmpInOffice)

  #return NumEmpInOffice/(n_weeks*daysInWeek)



In [15]:
HomeOfficeSimulation(n = 5, n_weeks = 2, verbose = True)

[4 3 0 1 2]
{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 0}
[2 2 2 2 2]
{0: 1, 1: 1, 2: 6, 3: 1, 4: 1, 5: 0}


array([0.1, 0.1, 0.6, 0.1, 0.1, 0. ])

In [ ]:
x1 = [4, 7, -5, 3]#this is a 1D array
x2 = [3, 5, 6, 1]#this is a 1D array

x1 + x2# the "+" operator for lists is an append operation !!
np.array(x1) + np.array(x2)
np.array(x1) * np.array(x2)
#It seems useful that we need numpy in adddition to lists!

#Why would we need pandas on top of numpy !!
y1 = np.array(x1)
y1[1]#numeric indexing
#y1["Wednesday"]#numpy cannot handle other ways of indexing !

p1 = pd.Series(y1, index = ["Monday", "Tuesday", "Wednesday", "Thursday"])
p1["Wednesday"]
p1[["Wednesday","Thursday"]]
"Wednesday" in p1
"Friday" in p1
p1
p1.to_dict()

In [ ]:
p1.array
p1.index

In [ ]:
one_sim = HomeOfficeSimulation(n_weeks= 500)

In [10]:
one_sim = HomeOfficeSimulation(n=6, n_weeks= 3, verbose=False)

In [11]:
np.sum(one_sim)

np.int64(10)

## Plots

What type of plot do we need ???

1. Histogram ?? Maybe not because there is no need for binning !
2. Simple bar plot !

In [ ]:
#let us plot !!
plt.figure(figsize=(7, 4))
plt.bar(np.arange(n+1),one_sim)
plt.xlabel("Number of employees in the office")
plt.ylabel("Probability")
plt.title(f"Distribution of employees in office (n={n})")
plt.grid(alpha=0.3)
plt.show()

In [ ]:
import seaborn as sns

sns.set()
sns.barplot(one_sim);

## Debugging

#### Sanity check:

1. Do the **probabilities add to one** ?

1. Read up on [pandas series](https://wesmckinney.com/book/pandas-basics#pandas_series)

2. Write basic code to double check our indexing logic !


In [ ]:
n=10
NumEmpInOffice = np.zeros(n+1, dtype = "int")
weekdays = [3,3]
#NumEmpInOffice[weekdays] += 1
for w in weekdays:
  NumEmpInOffice[w] += 1
print(NumEmpInOffice)

## Extensions

1. Fold the plotting code into the function
2. Make all "parameters" function arguments, e.g. *days_in_a_week* (5), *days_in_office* (2), ...
3. Can you use this code "as is" for the following related questions:
  
   a. Probability that two particular employees overlap ≥ 2 days

   b. Birthday problem

# pandas

data frames !!


In [ ]:
!pip install gapminder



In [ ]:
from gapminder import gapminder

In [ ]:
gapminder

In [ ]:
#what is the average lifeExp in this data set ?
#1 numpy:
np.mean(gapminder["lifeExp"])
np.mean(gapminder.lifeExp)



In [ ]:
#simple summaries are often insufficient to convey the complexities of the data !
#at the very least we might want to split the average by some sort of group
#what is the average lifeExp per continent ?
byContinent = gapminder.groupby("continent")
byContinent["lifeExp"].mean()
#this is called pivoting in many other softwares
